### ISSUE TITLE
Can't refresh token more than one time

### ISSUE THREAD

**Issue by htarwara6245** [telenordigital/connect-ios-sdk#16]
Here is my test statement : 
1.Login
2.It show user Info
3.Tapped "Refresh" which is refreshAccessToken() from oauth2Module
4.It returned the access token as we expected
5.Tapped "Refresh" again and it showed "Bad Request" Error
6.Then tapped "Refresh" again,it showed "oauth" error.
7.Then I can't Sign out anymore.

Any help?The app needs to be refreshing when the access token is expire.But,I cant refresh token more than one time.

Here is the sample which is changes of TelenorConnectIosHelloWorld project 

[TelenorConnectIosHelloWorld-master.zip](https://github.com/telenordigital/connect-ios-sdk/files/265708/TelenorConnectIosHelloWorld-master.zip)

Here is the preview of the problem : 

![refresh token](https://cloud.githubusercontent.com/assets/10526402/15282865/2de70a3a-1b6c-11e6-8e31-1433c46f2d18.gif)

**Comment by jorunfa** [comment]
Thanks for letting me know and providing me with example test and code. I will look closer at it soon.

**Comment by jorunfa** [comment]
I found the problem. When you got a new `refresh_token` it wan't getting saved: https://github.com/aerogear/aerogear-ios-oauth2/pull/42

It is fixed now in 02ba191. I'll make a new release shortly.

**Comment by htarwara6245** [comment]
I'll be waiting for your new release.Thanks.

**Comment by jorunfa** [comment]
The latest release contains the fix :) https://github.com/telenordigital/connect-ios-sdk/releases
