### ISSUE TITLE
Optional Params for disabling "Switch To Email" button

### ISSUE THREAD

**Issue by htarwara6245** [telenordigital/connect-ios-sdk#17]
Is there any optional params like "login_hint" that i can disable "Switch to Email" button at connect login web view?

**Comment by jorunfa** [comment]
It is not currently possible but we will make it so in the future. It will work so that you can provide a preferred username type, and then lock it down to that.

I will try to keep this issue up to date with the progress.

**Comment by htarwara6245** [comment]
Ok,thanks for the reply,waiting for that feature to apply.

**Comment by jorunfa** [comment]
Do you want this feature because you want to make sure the user registers his/her phone number?

If so you can use the [claims parameter](http://docs.telenordigital.com/apis/connect/id/authentication.html) to make sure they have to enter this.

**Comment by jorunfa** [comment]
Is this still an issue? I heard it might have been fixed by some other measure.

**Comment by htarwara6245** [comment]
Sorry,my late reply.It's already done on our client id.
