### ISSUE TITLE
Refresh token for Extension Support

### ISSUE THREAD

**Issue by htarwara6245** [telenordigital/connect-ios-sdk#21]
Please take a look,I think your library doesn't support Extension.

http://puu.sh/pLcU6/812fd03008.png

**Comment by htarwara6245** [comment]
I found it.Its because UIApplication.sharedApplication() is only supported inside the app not from the extension.So,can you add support for refreshing token via extension(notification center)?

**Comment by jorunfa** [comment]
How will your extension handle the situation where no user is signed in? Your extension can't open a Web View or anything like that, so how will you authenticate the user?

**Comment by htarwara6245** [comment]
Yeah,I know that situation.I will control it with NSUserDefault.
If the user signed in,the extension will check balance.If not,it will said to open the app and sign in.But,we are talking about refreshing user session right?

From what you explained about requestAccess(),there are 3 conditions.

- If it is not expired, you will get the one saved in keychain.
- If it is expired, but you have a refresh token, it will refresh the accessToken for you and give you that.
- If you don't have an accessToken or a refreshToken (if a user is not signed in) then it will sign in the user and then give you the accessToken.

What I want was the support for first and second condition which doesn't need to appear webview(Connect Sign in View) over UIApplication(Main App) if I am not wrong.

For the third one,it will be error callback.And I will check that error callback and notify the user if he or she need to log in again at Application from Extension.

So,if you can,I mean it was just a suggestion.Will you implement another SDKs which was only include support for Extension.

**Comment by jorunfa** [comment]
Okay, I think I see what you mean. I will need to discuss it with the team here.

**Comment by htarwara6245** [comment]
Thanks for the support!!!! If is there anything you need to know.Questions are welcome.

Best Regards
