### ISSUE TITLE
Custom Connect SDK Configuration Support for Access Token Expiry Duration Time

### ISSUE THREAD

**Issue by htarwara6245** [telenordigital/connect-ios-sdk#23]
Can you add configuration support at the SDK which we can set token duration to the Connect server?From what I am seeing right now,it expire after an hour.I want to make it higher than that time like 6hrs/time (then it will refresh token by opening the app) because of today extension support.

Since SDK methods are not available in Today Extension,we have to set token duration(expire time) to higher than 1hr.

Can we make configuration like that?If not,would you mind adding that support at SDK.

**Comment by jorunfa** [comment]
Hi!

Due to the specifications and security concerns regarding the OAuth 2 I'm not sure we can extend the duration of the Access Token. I will have to come back to you.
