### ISSUE TITLE
AccessToken not found

### ISSUE THREAD

**Issue by unazim84** [telenordigital/connect-ios-sdk#26]
When using staging, I set all information seeing TelenorConnectIosHelloWorld like:

let config = TelenorConnectConfig(clientId: "registered-client-id",
                                      redirectUrl: "registered-redirect-uri",
                                      useStaging: true,
                                      scopes: ["profile", "openid", "email"],
                                      accountId: "anything")

But I am getting this error: 

AccessToken not found
error=Optional(Error Domain=ResponseSerializerDomain Code=401 "unauthorized" UserInfo={NetworkingOperationFailingURLResponseErrorKey=<NSHTTPURLResponse: 0x7bf56070> { URL: https://connect.staging.telenordigital.com/oauth/token } { status code: 401, headers {
    "Access-Control-Allow-Methods" = "GET, POST, PUT, DELETE, OPTIONS";
    "Access-Control-Allow-Origin" = "*";
    Connection = "keep-alive";
    "Content-Length" = 77;
    "Content-Type" = "application/json";
    Date = "Sat, 06 Aug 2016 07:04:14 GMT";
    "Www-Authenticate" = "Basic realm=\"Telenor Digital Authorization Server\"";
    "X-Rate-Limit-Limit" = 500;
    "X-Rate-Limit-Window-Size-Ms" = 60000;
    "X-TELENORDIGITAL-REQUEST-ID" = "59-1470406639929-36540";
} }, NSLocalizedDescription=unauthorized, CustomData={
    error = "invalid_client";
    "error_description" = "Client authentication failed";
}, StatusCode=401})

How I can solve this issue and what is missing here?
 Thanks.

**Comment by jorunfa** [comment]
Hi! :)

I see that you're getting help from my colleague on email while I've been away on vacation, so I'm closing this issue. Please let us know if you're still having problems.

**Comment by unazim84** [comment]
Yes, still I have this problem. TelenorConnectIosHelloWorld is working fine. But why i am facing error when setting TelenorConnectConfig with another registered  client info?  what is missing here?

**Comment by jorunfa** [comment]
I am cc-ed on the mails Ulf has been sending you. Let us continue the discussion there. Please do not hesitate to send us further questions or inquires.

**Comment by roshanmoh** [comment]
Hi I'm also facing the same issue. Could you please help me in this matter ?

**Comment by jorunfa** [comment]
Hi. I'll try to help as best I can.

I believe the problem in this case was due to a public vs. confidential client mixup. Are you implementing a public or a confidential client? See https://github.com/telenordigital/connect-ios-sdk#confidential-client .

**Comment by roshanmoh** [comment]
Hi , 
It is actually Public Client. I just replace the configuration in sample app with my configurations. I'm getting response as follow

StatusCode=401, CustomData={
    error = "invalid_client";
    "error_description" = "Client authentication failed”;

**Comment by jorunfa** [comment]
It might be that you are using the wrong `clientId`. You can send me an email at jorund.fagerjord@telenordigital.com.

**Comment by roshanmoh** [comment]
Thanks Jorunafa... Issue was my account configuration. I managed to resolve the issue.
