### ISSUE TITLE
Any help with using new confidential client?

### ISSUE THREAD

**Issue by htarwara6245** [telenordigital/connect-ios-sdk#27]
Hi,I am having problem with using new feature confidential client.
Telenor gave us new confidential client id and some 14 bit key to bypass "Permission user allowances  page" which we know that user didn't need to click "Allow" after they log out and log in again.

```
let config = TelenorConnectConfig(clientId: "here we use confidential client id",
                                      redirectUrl: "confidential_client_id://connect/oauth2callback",
                                      useStaging: true,
                                      scopes:["email","phone"],
                                    isPublicClient : false)
```

So,where should we use the key which character count was 14.Any help?

**Comment by jorunfa** [comment]
Hi! :)

I think there is some misunderstanding here. In the case of confidential clients you need a third party server to hold the client secret, as it wouldn't be secret anymore if it was included in the native app code.

See https://github.com/telenordigital/connect-ios-sdk#advanced-usage and http://docs.telenordigital.com/connect/id/native_apps.html for more information about this.
