### ISSUE TITLE
JSONWebToken need to update CryptoSwift to 0.5.2 (Swift 2.2,2.3 Version)

### ISSUE THREAD

**Issue by htarwara6245** [telenordigital/connect-ios-sdk#30]
This connect SDK which use JSONWebToken need to update CryptoSwift to 0.5.2.
Please take a look

<img width="718" alt="screenshot 2016-11-08 12 04 13" src="https://cloud.githubusercontent.com/assets/10526402/20087878/c5d70624-a5aa-11e6-8f1b-7624497781f3.png">

I want to use CryptoSwift 0.5.2. But due to these circumstances,I can't update it.Can you set your JSONWebToken which used at connect SDK to Swift 2.2,2.3 CryptoSwift. 

If I am doing something wrong, can you help me out?

Thanks

**Comment by jorunfa** [comment]
Hi :). We're planning on updating the CryptoSwift package used by the SDK soon. I'll get back to you soon.

**Comment by jorunfa** [comment]
Unfortunately we are using JSONWebToken library version 1.5.0, which depends on CryptoSwift version 0.4.1. As far as I've found there isn't a way to use two different versions of the same library, it seems, and we can't change which version the CryptoSwift library depends upon.

There is a newer version of the JSONWebToken that uses a newer version of CryptoSwift. However, this is Swift version 3, so this will not work with the current version of the CONNECT iOS SDK.

We will be updating our SDK to Swift version 3 in the future, which means we will also update the CryptoSwift version. However, we can't do this until all the packages we depend upon are also updated to Swift 3. Hopefully this will be soon, as I believe the last remaining library we are depdendent has a Swift 3 version in development, but has not yet realeased this. When it is released we can also begin migrating to Swift 3.

I'll close this issue, but feel free to ask further questions and make new issues, of course :).
