### ISSUE TITLE
Integrating sdk as submodule to our existing project fails

### ISSUE THREAD

**Issue by bandhavivinay90** [telenordigital/connect-ios-sdk#41]
We tried to go with the submodule approach to add the connect id sdk in our existing xcode project, but it complains. All the steps mentioned are followed, but project seems to be not able to find AeroGeroHttp framework (which we get by running pod install over the directory).  Is there something expected to change on the framework search path ?

**Comment by jorunfa** [comment]
We recently updated to AeroGearHttp v2.0.0, and a correction of a few errors in the tests. See https://github.com/telenordigital/connect-ios-sdk/pull/42. Hopefully we will have a new version soon, which you can try.

**Comment by bandhavivinay90** [comment]
Perfect! We will wait till the pull request gets reviewed. Thanks.

**Comment by jorunfa** [comment]
New release out now - let me know how it goes
https://github.com/telenordigital/connect-ios-sdk/releases

**Comment by jorunfa** [comment]
Closing this due to old age/no reply.
