### ISSUE TITLE
Can't login for iOS 10

### ISSUE THREAD

**Issue by anikzaman123** [telenordigital/connect-ios-sdk#62]
When ever i try to login for lower iOS version e.g iOS 10 after send entering OTP code it  cant verify OTP  while its working just fine for iOS 11 or iOS 12.
<img width="385" alt="Screen Shot 2019-03-21 at 4 49 24 PM" src="https://user-images.githubusercontent.com/28537627/54747500-50707d00-4bf9-11e9-88ef-3785dc309ece.png">

**Comment by SerhiiBovtriuk** [comment]
This doesn't look like an issue anymore.
