### ISSUE TITLE
AuthURL creation crashes app

### ISSUE THREAD

**Issue by oscarkockum** [telenordigital/connect-ios-sdk#75]
OAuth2Module.swift adds an "optional" string as a parameter to the Auth URL and which makes it crash when the URL is created,

`     
let deviceId = UIDevice.current.identifierForVendor?.uuidString
`  
   
`      
if (deviceId != nil) {
            params += "&telenordigital_did=\(deviceId)"
        }
}
`     

Should be changed to something like this?

`     
if let id = UIDevice.current.identifierForVendor?.uuidString {
            params += "&telenordigital_did=\(id)"
}
`

Using Xcode 12.3,
iOS 14.3

**Comment by SerhiiBovtriuk** [comment]
Hello,

I believe this issue was fixed in a linked PR.
